import {RfCropType, RfSeasons} from '@/_data/_enums';
import {RfCrop} from '@/_data/_classes';

export const _crops = [
	new RfCrop({
		cropType: RfCropType.Crop,
		name: 'Turnip',
		goodSeasons: [RfSeasons.Summer, RfSeasons.Autumn],
		badSeasons: [],
		growTime: 3,
		tree: false,
		regrows: false,
		buyPrice: 200,
		sellPrice: 200,
		seedBuyPrice: 20,
		seedSellPrice: 2,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.Crop,
		name: 'Pink Turnip',
		goodSeasons: [RfSeasons.Spring],
		badSeasons: [],
		growTime: 11,
		tree: false,
		regrows: false,
		buyPrice: 700,
		sellPrice: 700,
		seedBuyPrice: 160,
		seedSellPrice: 16,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.Crop,
		name: 'Potato',
		goodSeasons: [RfSeasons.Spring, RfSeasons.Summer],
		badSeasons: [RfSeasons.Winter],
		growTime: 7,
		tree: false,
		regrows: false,
		buyPrice: 600,
		sellPrice: 600,
		seedBuyPrice: 80,
		seedSellPrice: 8,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.Crop,
		name: 'Spinach',
		goodSeasons: [RfSeasons.Autumn],
		badSeasons: [],
		growTime: 2,
		tree: false,
		regrows: false,
		buyPrice: 300,
		sellPrice: 300,
		seedBuyPrice: 60,
		seedSellPrice: 6,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.Crop,
		name: 'Radish',
		goodSeasons: [RfSeasons.Autumn],
		badSeasons: [RfSeasons.Summer],
		growTime: 5,
		tree: false,
		regrows: false,
		buyPrice: 1580,
		sellPrice: 1580,
		seedBuyPrice: 120,
		seedSellPrice: 12,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.Crop,
		name: 'Leek',
		goodSeasons: [RfSeasons.Spring, RfSeasons.Autumn],
		badSeasons: [RfSeasons.Summer],
		growTime: 9,
		tree: false,
		regrows: false,
		buyPrice: 4800,
		sellPrice: 4800,
		seedBuyPrice: 680,
		seedSellPrice: 68,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.Crop,
		name: 'Corn',
		goodSeasons: [RfSeasons.Spring, RfSeasons.Summer],
		badSeasons: [RfSeasons.Winter],
		growTime: 7,
		tree: false,
		regrows: false,
		buyPrice: 3000,
		sellPrice: 1000,
		seedBuyPrice: 450,
		seedSellPrice: 45,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.Crop,
		name: 'Yam',
		goodSeasons: [RfSeasons.Summer, RfSeasons.Autumn],
		badSeasons: [RfSeasons.Winter],
		growTime: 8,
		tree: false,
		regrows: false,
		buyPrice: 450,
		sellPrice: 450,
		seedBuyPrice: 250,
		seedSellPrice: 25,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.Crop,
		name: 'Carrot',
		goodSeasons: [RfSeasons.Autumn],
		badSeasons: [],
		growTime: 10,
		tree: false,
		regrows: false,
		buyPrice: 2600,
		sellPrice: 2600,
		seedBuyPrice: 400,
		seedSellPrice: 40,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.Crop,
		name: 'Cucumber',
		goodSeasons: [RfSeasons.Spring, RfSeasons.Summer],
		badSeasons: [RfSeasons.Winter],
		growTime: 5,
		tree: false,
		regrows: true,
		buyPrice: 250,
		sellPrice: 250,
		seedBuyPrice: 320,
		seedSellPrice: 32,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.Crop,
		name: 'Pumpkin',
		goodSeasons: [RfSeasons.Spring, RfSeasons.Summer],
		badSeasons: [RfSeasons.Winter],
		growTime: 7,
		tree: false,
		regrows: true,
		buyPrice: 420,
		sellPrice: 420,
		seedBuyPrice: 200,
		seedSellPrice: 20,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.Crop,
		name: 'Green Pepper',
		goodSeasons: [RfSeasons.Summer],
		badSeasons: [RfSeasons.Winter],
		growTime: 7,
		tree: false,
		regrows: true,
		buyPrice: 700,
		sellPrice: 700,
		seedBuyPrice: 800,
		seedSellPrice: 80,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.Crop,
		name: 'Tomato',
		goodSeasons: [RfSeasons.Spring, RfSeasons.Summer],
		badSeasons: [RfSeasons.Winter],
		growTime: 7,
		tree: false,
		regrows: true,
		buyPrice: 1800,
		sellPrice: 1800,
		seedBuyPrice: 1880,
		seedSellPrice: 188,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.Crop,
		name: 'Eggplant',
		goodSeasons: [RfSeasons.Spring, RfSeasons.Summer],
		badSeasons: [RfSeasons.Winter],
		growTime: 7,
		tree: false,
		regrows: true,
		buyPrice: 950,
		sellPrice: 950,
		seedBuyPrice: 720,
		seedSellPrice: 72,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.Crop,
		name: 'Bok Choy',
		goodSeasons: [RfSeasons.Autumn],
		badSeasons: [RfSeasons.Summer],
		growTime: 5,
		tree: false,
		regrows: false,
		buyPrice: 1900,
		sellPrice: 1900,
		seedBuyPrice: 1000,
		seedSellPrice: 100,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.Crop,
		name: 'Cabbage',
		goodSeasons: [RfSeasons.Spring, RfSeasons.Autumn],
		badSeasons: [],
		growTime: 8,
		tree: false,
		regrows: false,
		buyPrice: 2800,
		sellPrice: 2800,
		seedBuyPrice: 980,
		seedSellPrice: 98,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.Crop,
		name: 'Onion',
		goodSeasons: [RfSeasons.Autumn],
		badSeasons: [],
		growTime: 18,
		tree: false,
		regrows: false,
		buyPrice: 6700,
		sellPrice: 6700,
		seedBuyPrice: 1480,
		seedSellPrice: 148,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.Crop,
		name: 'Pink Melon',
		goodSeasons: [RfSeasons.Spring, RfSeasons.Summer],
		badSeasons: [RfSeasons.Winter],
		growTime: 7,
		tree: false,
		regrows: true,
		buyPrice: 5000,
		sellPrice: 5000,
		seedBuyPrice: 2120,
		seedSellPrice: 212,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.Crop,
		name: 'Hot-Hot Fruit',
		goodSeasons: [RfSeasons.Winter],
		badSeasons: [RfSeasons.Summer],
		growTime: 31,
		tree: false,
		regrows: false,
		buyPrice: 7000,
		sellPrice: 7000,
		seedBuyPrice: 1200,
		seedSellPrice: 120,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.Crop,
		name: 'Pineapple',
		goodSeasons: [RfSeasons.Summer],
		badSeasons: [RfSeasons.Spring, RfSeasons.Summer, RfSeasons.Spring, RfSeasons.Winter],
		growTime: 28,
		tree: false,
		regrows: true,
		buyPrice: 8500,
		sellPrice: 8500,
		seedBuyPrice: 2800,
		seedSellPrice: 280,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.Crop,
		name: 'Strawberry',
		goodSeasons: [RfSeasons.Spring, RfSeasons.Autumn],
		badSeasons: [],
		growTime: 16,
		tree: false,
		regrows: true,
		buyPrice: 800,
		sellPrice: 800,
		seedBuyPrice: 400,
		seedSellPrice: 40,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.Crop,
		name: 'Orange',
		goodSeasons: [RfSeasons.Spring, RfSeasons.Autumn],
		badSeasons: [RfSeasons.Winter],
		growTime: 22,
		tree: true,
		regrows: true,
		buyPrice: 500,
		sellPrice: 500,
		seedBuyPrice: 5000,
		seedSellPrice: 500,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.Crop,
		name: 'Grapes',
		goodSeasons: [RfSeasons.Spring, RfSeasons.Autumn],
		badSeasons: [RfSeasons.Winter],
		growTime: 50,
		tree: true,
		regrows: true,
		buyPrice: 650,
		sellPrice: 650,
		seedBuyPrice: 6000,
		seedSellPrice: 600,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.Crop,
		name: 'Apple',
		goodSeasons: [RfSeasons.Spring, RfSeasons.Autumn],
		badSeasons: [RfSeasons.Winter],
		growTime: 62,
		tree: true,
		regrows: true,
		buyPrice: 850,
		sellPrice: 850,
		seedBuyPrice: 7000,
		seedSellPrice: 700,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.Crop,
		name: 'Gold Potato',
		goodSeasons: [RfSeasons.Winter],
		badSeasons: [RfSeasons.Summer],
		growTime: 50,
		tree: false,
		regrows: false,
		buyPrice: 30000,
		sellPrice: 30000,
		seedBuyPrice: 4000,
		seedSellPrice: 400,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.Crop,
		name: 'Gold Pumpkin',
		goodSeasons: [RfSeasons.Winter],
		badSeasons: [RfSeasons.Summer],
		growTime: 70,
		tree: false,
		regrows: false,
		buyPrice: 20000,
		sellPrice: 20000,
		seedBuyPrice: 4500,
		seedSellPrice: 450,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.Crop,
		name: 'Gold Cabbage',
		goodSeasons: [RfSeasons.Winter],
		badSeasons: [RfSeasons.Summer],
		growTime: 90,
		tree: false,
		regrows: false,
		buyPrice: 50000,
		sellPrice: 50000,
		seedBuyPrice: 5000,
		seedSellPrice: null,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.Crop,
		name: 'Gold Turnip',
		goodSeasons: [RfSeasons.Winter],
		badSeasons: [RfSeasons.Summer],
		growTime: 120,
		tree: false,
		regrows: false,
		buyPrice: 100000,
		sellPrice: 100000,
		seedBuyPrice: 10000,
		seedSellPrice: 1000,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.Crop,
		name: 'Starfall Corn',
		goodSeasons: [RfSeasons.Summer],
		badSeasons: [RfSeasons.Spring, RfSeasons.Autumn, RfSeasons.Winter],
		growTime: 12,
		tree: false,
		regrows: false,
		buyPrice: 50000,
		sellPrice: 50000,
		seedBuyPrice: null,
		seedSellPrice: null,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.Crop,
		name: 'Starfall Pumpkin',
		goodSeasons: [RfSeasons.Autumn],
		badSeasons: [RfSeasons.Spring, RfSeasons.Summer, RfSeasons.Winter],
		growTime: 12,
		tree: false,
		regrows: false,
		buyPrice: 50000,
		sellPrice: 50000,
		seedBuyPrice: null,
		seedSellPrice: null,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.Crop,
		name: 'Starfall Potato',
		goodSeasons: [RfSeasons.Winter],
		badSeasons: [RfSeasons.Spring, RfSeasons.Summer, RfSeasons.Autumn],
		growTime: 12,
		tree: false,
		regrows: false,
		buyPrice: 50000,
		sellPrice: 50000,
		seedBuyPrice: null,
		seedSellPrice: null,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.Crop,
		name: 'Starfall Strawberry',
		goodSeasons: [RfSeasons.Spring],
		badSeasons: [RfSeasons.Summer, RfSeasons.Autumn, RfSeasons.Winter],
		growTime: 12,
		tree: false,
		regrows: false,
		buyPrice: 50000,
		sellPrice: 50000,
		seedBuyPrice: null,
		seedSellPrice: null,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.GiantCrop,
		name: 'Tyrant Turnip',
		goodSeasons: [RfSeasons.Summer, RfSeasons.Autumn],
		badSeasons: [],
		growTime: null,
		tree: false,
		regrows: false,
		buyPrice: 800,
		sellPrice: 200,
		seedBuyPrice: null,
		seedSellPrice: null,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.GiantCrop,
		name: 'Princely Potato',
		goodSeasons: [RfSeasons.Spring, RfSeasons.Summer],
		badSeasons: [RfSeasons.Winter],
		growTime: null,
		tree: false,
		regrows: false,
		buyPrice: 1600,
		sellPrice: 500,
		seedBuyPrice: null,
		seedSellPrice: null,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.GiantCrop,
		name: 'Sovereign Spinach',
		goodSeasons: [RfSeasons.Autumn],
		badSeasons: [],
		growTime: null,
		tree: false,
		regrows: false,
		buyPrice: 1000,
		sellPrice: 350,
		seedBuyPrice: null,
		seedSellPrice: null,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.GiantCrop,
		name: 'Doom Pumpkin',
		goodSeasons: [RfSeasons.Spring, RfSeasons.Summer],
		badSeasons: [RfSeasons.Winter],
		growTime: null,
		tree: false,
		regrows: true,
		buyPrice: 1560,
		sellPrice: 550,
		seedBuyPrice: null,
		seedSellPrice: null,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.GiantCrop,
		name: 'Noble Radish',
		goodSeasons: [RfSeasons.Autumn],
		badSeasons: [RfSeasons.Summer],
		growTime: null,
		tree: false,
		regrows: false,
		buyPrice: 5400,
		sellPrice: 2000,
		seedBuyPrice: null,
		seedSellPrice: null,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.GiantCrop,
		name: 'Legendary Leek',
		goodSeasons: [],
		badSeasons: [],
		growTime: null,
		tree: false,
		regrows: false,
		buyPrice: null,
		sellPrice: null,
		seedBuyPrice: null,
		seedSellPrice: null,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.GiantCrop,
		name: 'Sultan Strawberry',
		goodSeasons: [RfSeasons.Spring, RfSeasons.Autumn],
		badSeasons: [],
		growTime: null,
		tree: false,
		regrows: true,
		buyPrice: 2500,
		sellPrice: 700,
		seedBuyPrice: null,
		seedSellPrice: null,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.GiantCrop,
		name: 'Lordly Yam',
		goodSeasons: [RfSeasons.Summer, RfSeasons.Autumn],
		badSeasons: [RfSeasons.Winter],
		growTime: null,
		tree: false,
		regrows: false,
		buyPrice: 2200,
		sellPrice: 800,
		seedBuyPrice: null,
		seedSellPrice: null,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.GiantCrop,
		name: 'Colossal Pink',
		goodSeasons: [RfSeasons.Spring],
		badSeasons: [RfSeasons.Winter],
		growTime: null,
		tree: false,
		regrows: false,
		buyPrice: 3200,
		sellPrice: 1000,
		seedBuyPrice: null,
		seedSellPrice: null,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.GiantCrop,
		name: 'Kaiser Cucumber',
		goodSeasons: [RfSeasons.Spring, RfSeasons.Summer],
		badSeasons: [RfSeasons.Winter],
		growTime: null,
		tree: false,
		regrows: true,
		buyPrice: 980,
		sellPrice: 350,
		seedBuyPrice: null,
		seedSellPrice: null,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.GiantCrop,
		name: 'Royal Carrot',
		goodSeasons: [RfSeasons.Autumn],
		badSeasons: [],
		growTime: null,
		tree: false,
		regrows: false,
		buyPrice: 7000,
		sellPrice: 2000,
		seedBuyPrice: null,
		seedSellPrice: null,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.GiantCrop,
		name: 'Gigantic Corn',
		goodSeasons: [RfSeasons.Spring, RfSeasons.Summer],
		badSeasons: [RfSeasons.Winter],
		growTime: null,
		tree: false,
		regrows: false,
		buyPrice: 20000,
		sellPrice: 7500,
		seedBuyPrice: null,
		seedSellPrice: null,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.GiantCrop,
		name: 'Green Pepper Rex',
		goodSeasons: [RfSeasons.Summer],
		badSeasons: [RfSeasons.Winter],
		growTime: null,
		tree: false,
		regrows: true,
		buyPrice: 2300,
		sellPrice: 800,
		seedBuyPrice: null,
		seedSellPrice: null,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.GiantCrop,
		name: 'King Cabbage',
		goodSeasons: [RfSeasons.Spring, RfSeasons.Autumn],
		badSeasons: [],
		growTime: null,
		tree: false,
		regrows: false,
		buyPrice: 12000,
		sellPrice: 3400,
		seedBuyPrice: null,
		seedSellPrice: null,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.GiantCrop,
		name: 'Ultra Onion',
		goodSeasons: [RfSeasons.Autumn],
		badSeasons: [],
		growTime: null,
		tree: false,
		regrows: false,
		buyPrice: 16000,
		sellPrice: 4000,
		seedBuyPrice: null,
		seedSellPrice: null,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.GiantCrop,
		name: 'Boss Bok Choy',
		goodSeasons: [RfSeasons.Autumn],
		badSeasons: [RfSeasons.Summer],
		growTime: null,
		tree: false,
		regrows: false,
		buyPrice: null,
		sellPrice: 2250,
		seedBuyPrice: null,
		seedSellPrice: null,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.GiantCrop,
		name: 'Emperor Eggplant',
		goodSeasons: [RfSeasons.Spring, RfSeasons.Summer],
		badSeasons: [RfSeasons.Winter],
		growTime: null,
		tree: false,
		regrows: true,
		buyPrice: 3500,
		sellPrice: 1000,
		seedBuyPrice: null,
		seedSellPrice: null,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.GiantCrop,
		name: 'King Pineapple',
		goodSeasons: [RfSeasons.Summer],
		badSeasons: [RfSeasons.Spring, RfSeasons.Autumn, RfSeasons.Winter],
		growTime: null,
		tree: false,
		regrows: true,
		buyPrice: 28000,
		sellPrice: 8000,
		seedBuyPrice: null,
		seedSellPrice: null,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.GiantCrop,
		name: 'Titan Tomato',
		goodSeasons: [RfSeasons.Spring, RfSeasons.Summer],
		badSeasons: [RfSeasons.Winter],
		growTime: null,
		tree: false,
		regrows: true,
		buyPrice: 8000,
		sellPrice: 3000,
		seedBuyPrice: null,
		seedSellPrice: null,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.GiantCrop,
		name: 'Conqueror Melon',
		goodSeasons: [RfSeasons.Spring, RfSeasons.Summer],
		badSeasons: [RfSeasons.Winter],
		growTime: null,
		tree: false,
		regrows: true,
		buyPrice: 5000,
		sellPrice: 850,
		seedBuyPrice: null,
		seedSellPrice: null,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.GiantCrop,
		name: 'King Hot Hot Fruit',
		goodSeasons: [RfSeasons.Winter],
		badSeasons: [RfSeasons.Summer],
		growTime: null,
		tree: false,
		regrows: false,
		buyPrice: 16000,
		sellPrice: 4500,
		seedBuyPrice: null,
		seedSellPrice: null,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.GiantCrop,
		name: 'Golden Doom Pumpkin',
		goodSeasons: [RfSeasons.Winter],
		badSeasons: [RfSeasons.Summer],
		growTime: null,
		tree: false,
		regrows: true,
		buyPrice: 80000,
		sellPrice: 18000,
		seedBuyPrice: null,
		seedSellPrice: null,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.GiantCrop,
		name: 'Gold Prince Potato',
		goodSeasons: [RfSeasons.Winter],
		badSeasons: [RfSeasons.Summer],
		growTime: null,
		tree: false,
		regrows: false,
		buyPrice: 100000,
		sellPrice: 27000,
		seedBuyPrice: null,
		seedSellPrice: null,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.GiantCrop,
		name: 'Gold King Cabbage',
		goodSeasons: [RfSeasons.Winter],
		badSeasons: [RfSeasons.Summer],
		growTime: null,
		tree: false,
		regrows: false,
		buyPrice: 200000,
		sellPrice: 52000,
		seedBuyPrice: null,
		seedSellPrice: null,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.GiantCrop,
		name: 'Gold Tyrant Turnip',
		goodSeasons: [RfSeasons.Winter],
		badSeasons: [RfSeasons.Summer],
		growTime: null,
		tree: false,
		regrows: false,
		buyPrice: 500000,
		sellPrice: 90000,
		seedBuyPrice: null,
		seedSellPrice: null,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.Flower,
		name: 'Toyherb',
		goodSeasons: [RfSeasons.Spring],
		badSeasons: [RfSeasons.Winter],
		growTime: 4,
		tree: false,
		regrows: false,
		buyPrice: 250,
		sellPrice: 65,
		seedBuyPrice: 60,
		seedSellPrice: 6,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.Flower,
		name: 'Pink Cat',
		goodSeasons: [RfSeasons.Summer],
		badSeasons: [RfSeasons.Winter],
		growTime: 6,
		tree: false,
		regrows: false,
		buyPrice: 450,
		sellPrice: 110,
		seedBuyPrice: 180,
		seedSellPrice: 18,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.Flower,
		name: 'Moondrop',
		goodSeasons: [RfSeasons.Spring, RfSeasons.Autumn],
		badSeasons: [RfSeasons.Winter],
		growTime: 7,
		tree: false,
		regrows: false,
		buyPrice: 400,
		sellPrice: 115,
		seedBuyPrice: 250,
		seedSellPrice: 25,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.Flower,
		name: 'Charm Blue',
		goodSeasons: [RfSeasons.Autumn],
		badSeasons: [RfSeasons.Winter],
		growTime: 8,
		tree: false,
		regrows: false,
		buyPrice: 800,
		sellPrice: 220,
		seedBuyPrice: 370,
		seedSellPrice: 37,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.Flower,
		name: 'Cherry Grass',
		goodSeasons: [RfSeasons.Spring],
		badSeasons: [RfSeasons.Winter],
		growTime: 10,
		tree: false,
		regrows: false,
		buyPrice: 700,
		sellPrice: 230,
		seedBuyPrice: 420,
		seedSellPrice: 42,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.Flower,
		name: 'Lamp Grass',
		goodSeasons: [RfSeasons.Winter],
		badSeasons: [],
		growTime: 16,
		tree: false,
		regrows: false,
		buyPrice: 2000,
		sellPrice: 650,
		seedBuyPrice: 740,
		seedSellPrice: 74,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.Flower,
		name: 'Ironleaf',
		goodSeasons: [RfSeasons.Winter],
		badSeasons: [RfSeasons.Summer],
		growTime: 21,
		tree: false,
		regrows: false,
		buyPrice: 4444,
		sellPrice: 1111,
		seedBuyPrice: 600,
		seedSellPrice: 60,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.Flower,
		name: 'Autumn Grass',
		goodSeasons: [RfSeasons.Autumn],
		badSeasons: [RfSeasons.Winter],
		growTime: 29,
		tree: false,
		regrows: false,
		buyPrice: 6000,
		sellPrice: 1800,
		seedBuyPrice: 2500,
		seedSellPrice: 250,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.Flower,
		name: 'Four Leaf Clover',
		goodSeasons: [RfSeasons.Autumn],
		badSeasons: [RfSeasons.Summer],
		growTime: 28,
		tree: false,
		regrows: false,
		buyPrice: 4000,
		sellPrice: 980,
		seedBuyPrice: 960,
		seedSellPrice: 96,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.Flower,
		name: 'Fireflower',
		goodSeasons: [RfSeasons.Summer],
		badSeasons: [RfSeasons.Winter],
		growTime: 42,
		tree: false,
		regrows: false,
		buyPrice: 10000,
		sellPrice: 2800,
		seedBuyPrice: 5000,
		seedSellPrice: 500,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.Flower,
		name: 'Pom-Pom Grass',
		goodSeasons: [RfSeasons.Autumn],
		badSeasons: [RfSeasons.Winter],
		growTime: 14,
		tree: false,
		regrows: false,
		buyPrice: 1500,
		sellPrice: 440,
		seedBuyPrice: 510,
		seedSellPrice: 51,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.Flower,
		name: 'Noel Grass',
		goodSeasons: [RfSeasons.Spring],
		badSeasons: [RfSeasons.Summer],
		growTime: 33,
		tree: false,
		regrows: false,
		buyPrice: 6600,
		sellPrice: 2000,
		seedBuyPrice: 2700,
		seedSellPrice: 270,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.Flower,
		name: 'Blue Crystal',
		goodSeasons: [RfSeasons.Spring],
		badSeasons: [RfSeasons.Summer, RfSeasons.Autumn, RfSeasons.Winter],
		growTime: 55,
		tree: false,
		regrows: false,
		buyPrice: 40000,
		sellPrice: 15000,
		seedBuyPrice: 30000,
		seedSellPrice: 1000,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.Flower,
		name: 'Green Crystal',
		goodSeasons: [RfSeasons.Summer],
		badSeasons: [RfSeasons.Spring, RfSeasons.Autumn, RfSeasons.Winter],
		growTime: 70,
		tree: false,
		regrows: false,
		buyPrice: 48000,
		sellPrice: 17000,
		seedBuyPrice: 30000,
		seedSellPrice: 1000,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.Flower,
		name: 'Red Crystal',
		goodSeasons: [RfSeasons.Autumn],
		badSeasons: [RfSeasons.Spring, RfSeasons.Summer, RfSeasons.Winter],
		growTime: 80,
		tree: false,
		regrows: false,
		buyPrice: 56000,
		sellPrice: 20000,
		seedBuyPrice: 30000,
		seedSellPrice: 1000,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.Flower,
		name: 'White Crystal',
		goodSeasons: [RfSeasons.Winter],
		badSeasons: [RfSeasons.Spring, RfSeasons.Summer, RfSeasons.Autumn],
		growTime: 90,
		tree: false,
		regrows: false,
		buyPrice: 80000,
		sellPrice: 22500,
		seedBuyPrice: 30000,
		seedSellPrice: 1000,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.Flower,
		name: 'Emery Flower',
		goodSeasons: [],
		badSeasons: [],
		growTime: 120,
		tree: false,
		regrows: false,
		buyPrice: 500000,
		sellPrice: 55000,
		seedBuyPrice: 50000,
		seedSellPrice: 2500,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.GiantFlower,
		name: 'Ultra Toyherb',
		goodSeasons: [RfSeasons.Spring],
		badSeasons: [RfSeasons.Winter],
		growTime: 4,
		tree: false,
		regrows: false,
		buyPrice: 1500,
		sellPrice: 350,
		seedBuyPrice: null,
		seedSellPrice: null,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.GiantFlower,
		name: 'Ultra Moondrop',
		goodSeasons: [RfSeasons.Spring, RfSeasons.Autumn],
		badSeasons: [RfSeasons.Winter],
		growTime: 7,
		tree: false,
		regrows: false,
		buyPrice: 2000,
		sellPrice: 650,
		seedBuyPrice: null,
		seedSellPrice: null,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.GiantFlower,
		name: 'King Pink Cat',
		goodSeasons: [RfSeasons.Summer],
		badSeasons: [RfSeasons.Winter],
		growTime: 6,
		tree: false,
		regrows: false,
		buyPrice: 2200,
		sellPrice: 600,
		seedBuyPrice: null,
		seedSellPrice: null,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.GiantFlower,
		name: 'Great Charm Blue',
		goodSeasons: [RfSeasons.Autumn],
		badSeasons: [RfSeasons.Winter],
		growTime: 8,
		tree: false,
		regrows: false,
		buyPrice: 4000,
		sellPrice: 1200,
		seedBuyPrice: null,
		seedSellPrice: null,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.GiantFlower,
		name: 'King Cherry Grass',
		goodSeasons: [RfSeasons.Spring],
		badSeasons: [RfSeasons.Winter],
		growTime: 10,
		tree: false,
		regrows: false,
		buyPrice: 3800,
		sellPrice: 1200,
		seedBuyPrice: null,
		seedSellPrice: null,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.GiantFlower,
		name: 'Kaiser Lamp Grass',
		goodSeasons: [RfSeasons.Winter],
		badSeasons: [],
		growTime: 16,
		tree: false,
		regrows: false,
		buyPrice: 8500,
		sellPrice: 3250,
		seedBuyPrice: null,
		seedSellPrice: null,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.GiantFlower,
		name: 'Super Ironleaf',
		goodSeasons: [RfSeasons.Winter],
		badSeasons: [RfSeasons.Summer],
		growTime: 21,
		tree: false,
		regrows: false,
		buyPrice: 22222,
		sellPrice: 5555,
		seedBuyPrice: null,
		seedSellPrice: null,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.GiantFlower,
		name: 'Great 4-Leaf Clover',
		goodSeasons: [RfSeasons.Spring, RfSeasons.Autumn],
		badSeasons: [RfSeasons.Summer],
		growTime: 28,
		tree: false,
		regrows: false,
		buyPrice: 20000,
		sellPrice: 5000,
		seedBuyPrice: null,
		seedSellPrice: null,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.GiantFlower,
		name: 'Big Fireflower',
		goodSeasons: [RfSeasons.Summer],
		badSeasons: [RfSeasons.Winter],
		growTime: 42,
		tree: false,
		regrows: false,
		buyPrice: 50000,
		sellPrice: 14000,
		seedBuyPrice: null,
		seedSellPrice: null,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.GiantFlower,
		name: 'Large Noel Grass',
		goodSeasons: [RfSeasons.Winter],
		badSeasons: [RfSeasons.Summer],
		growTime: 33,
		tree: false,
		regrows: false,
		buyPrice: 33300,
		sellPrice: 10000,
		seedBuyPrice: null,
		seedSellPrice: null,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.GiantFlower,
		name: 'Big Autumn Grass',
		goodSeasons: [RfSeasons.Autumn],
		badSeasons: [RfSeasons.Winter],
		growTime: 29,
		tree: false,
		regrows: false,
		buyPrice: 30000,
		sellPrice: 9000,
		seedBuyPrice: null,
		seedSellPrice: null,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.GiantFlower,
		name: 'King Pom-Pom Grass',
		goodSeasons: [RfSeasons.Autumn],
		badSeasons: [RfSeasons.Winter],
		growTime: 14,
		tree: false,
		regrows: false,
		buyPrice: 7000,
		sellPrice: 2300,
		seedBuyPrice: null,
		seedSellPrice: null,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.GiantFlower,
		name: 'Big Blue Crystal',
		goodSeasons: [RfSeasons.Spring],
		badSeasons: [RfSeasons.Summer, RfSeasons.Autumn, RfSeasons.Winter],
		growTime: 55,
		tree: false,
		regrows: false,
		buyPrice: 200000,
		sellPrice: 67500,
		seedBuyPrice: null,
		seedSellPrice: null,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.GiantFlower,
		name: 'Big Green Crystal',
		goodSeasons: [RfSeasons.Summer],
		badSeasons: [RfSeasons.Spring, RfSeasons.Autumn, RfSeasons.Winter],
		growTime: 70,
		tree: false,
		regrows: false,
		buyPrice: 240000,
		sellPrice: 76500,
		seedBuyPrice: null,
		seedSellPrice: null,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.GiantFlower,
		name: 'Big Red Crystal',
		goodSeasons: [RfSeasons.Autumn],
		badSeasons: [RfSeasons.Spring, RfSeasons.Summer, RfSeasons.Winter],
		growTime: 80,
		tree: false,
		regrows: false,
		buyPrice: 280000,
		sellPrice: 90000,
		seedBuyPrice: null,
		seedSellPrice: null,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.GiantFlower,
		name: 'Big White Crystal',
		goodSeasons: [RfSeasons.Winter],
		badSeasons: [RfSeasons.Spring, RfSeasons.Summer, RfSeasons.Autumn],
		growTime: 90,
		tree: false,
		regrows: false,
		buyPrice: 400000,
		sellPrice: 101500,
		seedBuyPrice: null,
		seedSellPrice: null,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.GiantFlower,
		name: 'Great Emery Flower',
		goodSeasons: [],
		badSeasons: [],
		growTime: 120,
		tree: false,
		regrows: false,
		buyPrice: 1000000,
		sellPrice: 250000,
		seedBuyPrice: null,
		seedSellPrice: null,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.Other,
		name: 'Fodder',
		goodSeasons: [],
		badSeasons: [],
		growTime: null,
		tree: false,
		regrows: true,
		buyPrice: null,
		sellPrice: null,
		seedBuyPrice: 30,
		seedSellPrice: 3,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.Other,
		name: 'Sword Flower',
		goodSeasons: [],
		badSeasons: [],
		growTime: null,
		tree: false,
		regrows: false,
		buyPrice: null,
		sellPrice: null,
		seedBuyPrice: 1500,
		seedSellPrice: 150,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.Other,
		name: 'Shield Flower',
		goodSeasons: [],
		badSeasons: [],
		growTime: null,
		tree: false,
		regrows: false,
		buyPrice: null,
		sellPrice: null,
		seedBuyPrice: 1500,
		seedSellPrice: 150,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.Other,
		name: 'Twinkle Tree',
		goodSeasons: [],
		badSeasons: [RfSeasons.Winter],
		growTime: null,
		tree: true,
		regrows: false,
		buyPrice: 300,
		sellPrice: 3000,
		seedBuyPrice: 3000,
		seedSellPrice: 300,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.Other,
		name: 'Starfall Seeds',
		goodSeasons: [],
		badSeasons: [],
		growTime: null,
		tree: false,
		regrows: false,
		buyPrice: null,
		sellPrice: null,
		seedBuyPrice: null,
		seedSellPrice: null,
		locations: []
	}),
	new RfCrop({
		cropType: RfCropType.Wild,
		name: 'Bamboo Sprout',
		goodSeasons: [],
		badSeasons: [],
		growTime: null,
		tree: false,
		regrows: false,
		buyPrice: 200,
		sellPrice: 40,
		seedBuyPrice: null,
		seedSellPrice: null,
		locations: ['Farm']
	}),
	new RfCrop({
		cropType: RfCropType.Wild,
		name: 'Mushroom',
		goodSeasons: [],
		badSeasons: [],
		growTime: null,
		tree: false,
		regrows: false,
		buyPrice: 2000,
		sellPrice: 10,
		seedBuyPrice: null,
		seedSellPrice: null,
		locations: ['Forres Forest Area']
	}),
	new RfCrop({
		cropType: RfCropType.Wild,
		name: 'Monarch Mushroom',
		goodSeasons: [],
		badSeasons: [],
		growTime: null,
		tree: false,
		regrows: false,
		buyPrice: null,
		sellPrice: 10000,
		seedBuyPrice: null,
		seedSellPrice: null,
		locations: ['Dropped by Death Fungus', 'Tricky Muck']
	}),
	new RfCrop({
		cropType: RfCropType.Wild,
		name: 'Mealy Apple',
		goodSeasons: [],
		badSeasons: [],
		growTime: null,
		tree: false,
		regrows: false,
		buyPrice: null,
		sellPrice: 3000,
		seedBuyPrice: null,
		seedSellPrice: null,
		locations: ['Dark Griffin (spawns during Meteor Weather)']
	}),
	new RfCrop({
		cropType: RfCropType.Wild,
		name: 'Medicinal Herb',
		goodSeasons: [],
		badSeasons: [],
		growTime: null,
		tree: false,
		regrows: false,
		buyPrice: 80,
		sellPrice: 8,
		seedBuyPrice: null,
		seedSellPrice: null,
		locations: ['Farm']
	}),
	new RfCrop({
		cropType: RfCropType.Wild,
		name: 'Antidote Grass',
		goodSeasons: [],
		badSeasons: [],
		growTime: null,
		tree: false,
		regrows: false,
		buyPrice: 150,
		sellPrice: 6,
		seedBuyPrice: null,
		seedSellPrice: null,
		locations: ['Farm']
	}),
	new RfCrop({
		cropType: RfCropType.Wild,
		name: 'Black Grass',
		goodSeasons: [],
		badSeasons: [],
		growTime: null,
		tree: false,
		regrows: false,
		buyPrice: 120,
		sellPrice: 5,
		seedBuyPrice: null,
		seedSellPrice: null,
		locations: ['Farm', 'Cherub Volcanic Area']
	}),
	new RfCrop({
		cropType: RfCropType.Wild,
		name: 'Orange Grass',
		goodSeasons: [],
		badSeasons: [],
		growTime: null,
		tree: false,
		regrows: false,
		buyPrice: 120,
		sellPrice: 5,
		seedBuyPrice: null,
		seedSellPrice: null,
		locations: ['Farm', 'Forres Forest Area', 'Remains of Thief King\'s Hideout']
	}),
	new RfCrop({
		cropType: RfCropType.Wild,
		name: 'Red Grass',
		goodSeasons: [],
		badSeasons: [],
		growTime: null,
		tree: false,
		regrows: false,
		buyPrice: 120,
		sellPrice: 5,
		seedBuyPrice: null,
		seedSellPrice: null,
		locations: ['Farm', 'Gadius Plain']
	}),
	new RfCrop({
		cropType: RfCropType.Wild,
		name: 'Yellow Grass',
		goodSeasons: [],
		badSeasons: [],
		growTime: null,
		tree: false,
		regrows: false,
		buyPrice: 120,
		sellPrice: 5,
		seedBuyPrice: null,
		seedSellPrice: null,
		locations: ['Farm', 'Gadius Plain', 'Basara\'s Hideout']
	}),
	new RfCrop({
		cropType: RfCropType.Wild,
		name: 'Blue Grass',
		goodSeasons: [],
		badSeasons: [],
		growTime: null,
		tree: false,
		regrows: false,
		buyPrice: 120,
		sellPrice: 5,
		seedBuyPrice: null,
		seedSellPrice: null,
		locations: ['Farm', 'Forres Forest Area', 'Gadius Plain', 'Cloudheim']
	}),
	new RfCrop({
		cropType: RfCropType.Wild,
		name: 'Green Grass',
		goodSeasons: [],
		badSeasons: [],
		growTime: null,
		tree: false,
		regrows: false,
		buyPrice: 120,
		sellPrice: 5,
		seedBuyPrice: null,
		seedSellPrice: null,
		locations: ['Farm', 'Forres Forest Area']
	}),
	new RfCrop({
		cropType: RfCropType.Wild,
		name: 'Purple Grass',
		goodSeasons: [],
		badSeasons: [],
		growTime: null,
		tree: false,
		regrows: false,
		buyPrice: 120,
		sellPrice: 5,
		seedBuyPrice: null,
		seedSellPrice: null,
		locations: ['Farm', 'Meline Ice Cave']
	}),
	new RfCrop({
		cropType: RfCropType.Wild,
		name: 'Indigo Grass',
		goodSeasons: [],
		badSeasons: [],
		growTime: null,
		tree: false,
		regrows: false,
		buyPrice: 120,
		sellPrice: 5,
		seedBuyPrice: null,
		seedSellPrice: null,
		locations: ['Farm', 'Cherub Volcanic Area', 'Cloudheim']
	}),
	new RfCrop({
		cropType: RfCropType.Wild,
		name: 'White Grass',
		goodSeasons: [],
		badSeasons: [],
		growTime: null,
		tree: false,
		regrows: false,
		buyPrice: 120,
		sellPrice: 5,
		seedBuyPrice: null,
		seedSellPrice: null,
		locations: ['Farm', 'Lake Yumina', 'Thunder Wilderness']
	}),
	new RfCrop({
		cropType: RfCropType.Wild,
		name: 'Weeds',
		goodSeasons: [],
		badSeasons: [],
		growTime: null,
		tree: false,
		regrows: false,
		buyPrice: 30,
		sellPrice: 1,
		seedBuyPrice: null,
		seedSellPrice: null,
		locations: ['Farm']
	}),
	new RfCrop({
		cropType: RfCropType.Wild,
		name: 'Withered Grass',
		goodSeasons: [],
		badSeasons: [],
		growTime: null,
		tree: false,
		regrows: false,
		buyPrice: 100,
		sellPrice: 1,
		seedBuyPrice: null,
		seedSellPrice: null,
		locations: ['Farm']
	}),
	new RfCrop({
		cropType: RfCropType.Wild,
		name: 'Ayngondaia Lawn',
		goodSeasons: [],
		badSeasons: [],
		growTime: null,
		tree: false,
		regrows: false,
		buyPrice: null,
		sellPrice: 33,
		seedBuyPrice: null,
		seedSellPrice: null,
		locations: ['Skull Dragon drop']
	}),
	new RfCrop({
		cropType: RfCropType.Wild,
		name: 'Elli Leaves',
		goodSeasons: [],
		badSeasons: [],
		growTime: null,
		tree: false,
		regrows: false,
		buyPrice: 3500,
		sellPrice: 250,
		seedBuyPrice: null,
		seedSellPrice: null,
		locations: ['Cloudheim']
	})
];
